#!/usr/bin/env bash
# This script displays "Best School" 10 times, saying "Hi" at the 9th iteration
COUNTER=1
while [ $COUNTER -le 10 ]; do
  echo "Best School"
  if [ $COUNTER -eq 9 ]; then
    echo "Hi"
  fi
  COUNTER=$((COUNTER + 1))
done
