#!/usr/bin/env bash
# This script loops from 1 to 10 displaying different messages based on the count
COUNTER=1
while [ $COUNTER -le 10 ]; do
  if [ $COUNTER -eq 4 ]; then
    echo "bad luck"
  elif [ $COUNTER -eq 8 ]; then
    echo "good luck"
  else
    echo "Best School"
  fi
  COUNTER=$((COUNTER + 1))
done
