#!/usr/bin/env bash
# This script displays numbers 1 to 20 with specific "bad luck" messages using a case statement
COUNTER=1
while [ $COUNTER -le 20 ]; do
  case $COUNTER in
    4)
      echo $COUNTER
      echo "bad luck from China"
      ;;
    9)
      echo $COUNTER
      echo "bad luck from Japan"
      ;;
    17)
      echo $COUNTER
      echo "bad luck from Italy"
      ;;
    *)
      echo $COUNTER
      ;;
  esac
  COUNTER=$((COUNTER + 1))
done
